### ISSUE TITLE
CRUD Dominios

### ISSUE THREAD

**Issue by mweitzman** [walaland/kolbanaizer#21]
Dificultad: :large_blue_circle: (fácil)
Importacia: :1st_place_medal: (importante)

- Implementar 4 lambdas para agregar, buscarn actualizar y eliminar dominios.
- Lambdas reciben conexión a la base de datos, request y response.
- Lambdas deben ser implementados en archivos separados en `client/lambdas/`

```node
module.exports = (req, res, db) => {
	/* Implementacion */
};
```

Parámetros y observaciones adicionales deben ser _documentados_ en este thread.
Suerte programando :desktop_computer:

**Comment by Goferk** [comment]
# Crear dominio
**Ruta:** `/createDomain`
**Body:**

| Parámetro | Valor | Tipo | Default |
|:-:|:-:|:-:|:-:|
| netloc | Nombre del dominio | String | - |
| schema | Protocolo del dominio | String | 'http' |
| rank | Ranking del dominio | Float | 0 |
| whitelist | 0/1 | Int | 0 |
| blacklist | 0/1 | Int | 0 |

Si `whitelist = 1` y `blacklist = 1` entonces se guardara `whitelist = 0`.

**Retorno:**
Si se logra insertar en la tabla retorna status 200, si arroja error retorna status 400.

# Obtener dominio específico por ID
**Ruta:** `/readDomain`
**Body:**

| Parámetro | Valor | Tipo | Default |
|:-:|:-:|:-:|:-:|
| id | ID asociada al dominio | Int | - |

**Retorno:**
Si se logra encontrar la id en la tabla, retorna una lista de un elemento, el cual es un objeto que contiene los nombres de las columnas con sus valores. Si arroja error retorna status 404.

# Obtener dominio específico por ID
**Ruta:** `/readDomain`
**Query:**

| Parámetro | Valor | Tipo | Default |
|:-:|:-:|:-:|:-:|
| id | ID asociada al dominio | Int | - |

**Retorno:**
Si se logra encontrar la id en la tabla, retorna una lista de un elemento, el cual es un objeto que contiene los nombres de las columnas con sus valores. Si arroja error retorna status 404.

# Obtener dominios
**Ruta:** `/readDomains`
**Query:**

| Parámetro | Valor | Tipo | Default |
|:-:|:-:|:-:|:-:|
| netloc | Parte del nombre del dominio | String | '' |

**Retorno:**
Si se logra encontrar la id en la tabla, retorna una lista de un elemento, el cual es un objeto que contiene los nombres de las columnas con sus valores. Si arroja error retorna status 404.

# Editar dominio
**Ruta:** `/updateDomain`
**Body:**

| Parámetro | Valor | Tipo | Default |
|:-:|:-:|:-:|:-:|
| id | ID asociada al dominio | Int | - |
| netloc | Nombre del dominio | String | - |
| schema | Protocolo del dominio | String | 'http' |
| rank | Ranking del dominio | Float | 0 |
| whitelist | 0/1 | Int | 0 |
| blacklist | 0/1 | Int | 0 |

Si `whitelist = 1` y `blacklist = 1` entonces se guardara `whitelist = 0`.

**Retorno:**
Si se logra editar la fila en la tabla, retorna status 200. Si arroja error retorna status 503.

# Eliminar dominio
**Ruta:** `/deleteDomain`
**Body:**

| Parámetro | Valor | Tipo | Default |
|:-:|:-:|:-:|:-:|
| id | ID asociada al dominio | Int | - |

**Retorno:**
Si se logra eliminar la fila en la tabla, retorna status 200. Si arroja error retorna status 503.
