### ISSUE TITLE
CRUD índice de artefactos

### ISSUE THREAD

**Issue by mweitzman** [walaland/kolbanaizer#24]
Dificultad: :large_blue_circle: (fácil)
Importacia: :1st_place_medal: (importante)

- Implementar 4 lambdas para agregar, buscarn actualizar y eliminar artefactos (las referencias a ellos).
- Lambdas reciben conexión a la base de datos, request y response.
- Lambdas deben ser implementados en archivos separados en `client/lambdas/`

```node
module.exports = (req, res, db) => {
	/* Implementacion */
};
```

Parámetros y observaciones adicionales deben ser _documentados_ en este thread.
Suerte programando :desktop_computer:

**Comment by mweitzman** [comment]
Notar la relación que existe con #23

**Comment by Goferk** [comment]
# Crear artefacto
**Ruta:** `/lambda/createArtifact`
**Body:**

| Parámetro | Valor | Tipo | Default |
|:-:|:-:|:-:|:-:|
| netloc | Nombre del dominio del artefacto | String | null |
| schema | Protocolo del dominio del artefacto | String | 'http' |
| rank | Ranking del dominio | Float | 0 |
| whitelist | 0/1 | Int | 0 |
| blacklist | 0/1 | Int | 0 |
| path | Path del artefacto | String | null |
| params | Params del artefacto | String | null |
| query | Query del artefacto | String | null |
| fragment | Fragment del artefacto | String | null |
| type | Tipo de artefacto | String | null |
| size | Tamaño del artefacto | Int | null |
| last_modified | Última modificación del artefacto | Datetime | null |
| route | Ruta local del artefacto | String | null |


- Si `whitelist = 1` y `blacklist = 1` entonces se guardara `whitelist = 0`.
- Debe existir al menos `netloc` o `route` para insertar el artefacto.
- Dado que los atributos `null` no son comparables, se puede insertar un mismo artefacto varias veces en la tabla, tener precaución con esto.

**Retorno:**
Si se logra insertar en la tabla retorna status 200, si arroja error retorna status 400.

**Comment by mweitzman** [comment]
No buscar artefacto, eso se hace en #20
