### ISSUE TITLE
Lambda de descarga de artefactos

### ISSUE THREAD

**Issue by mweitzman** [walaland/kolbanaizer#25]
Dificultad: :white_circle: (media)
Importacia: :2nd_place_medal: : (no crítica)

- Implementar un lambda que recibe una url de un artefacto.
- Lo descarga y almacena offline.
- Guarda la referencia al archivo local en la base de datos.

```node
module.exports = (req, res, db) => {
	/* Implementacion */
};
```

Parámetros y observaciones adicionales deben ser _documentados_ en este thread.
Suerte programando :desktop_computer:

**Comment by mweitzman** [comment]
Relacionado con #23

**Comment by Danielromanv** [comment]
Ahora además del enlace requiere de la id del artefacto, para facilitar el proceso de guardar la ruta en la tabla de artefactos.
