### ISSUE TITLE
Crawler de Artefactos

### ISSUE THREAD

**Issue by mweitzman** [walaland/kolbanaizer#6]
- Implementar el módulo AtrifactCrawler
- Debe incluir la función crawl(), la cual recibe los parámetros que estiman necesarios, como urls y realiza una búsqueda _"recursiva"_ (ver módulo WebGraph) de artefactos.
- No debe descargarlos, sino que crear un índice de ellos, por ahora un diccionario que es retornado.
- Debe ser fácilmente adaptable. En el futuro, cada nuevo artefacto debe ser agregado a la base de datos, por lo que se debe tener eso en consideración.
- Es necesario que dicho crawler extraiga al menos:
    - Nombre de dominio
    - URL completa al archivo
    - Extensión del archivo
    - Alguna fecha asociada a la última edición archivo (o similar)
- Notar que pueden descargar el archivo a RAM (siempre que no sea demasiado grande) para analizarlo sin la necesidad de descargarlo a disco.

_Que las probabilidades siempre estén a su favor_

**Comment by Goferk** [comment]
artifactCrawler(url, max_nodes=1E8, pending=queue(maxsize=1E8), display=False)
**url**: Url de donde se quiere extraer artefactos
**max_nodes**: Tope máximo de artefactos a recolectar del dominio (se recomienda 1E2 para pruebas)
**pending**: Tope máximo de artefactos que pueden quedar en cola
**display**: True si se quiere ver cuanto lleva de búsqueda, omitir si no se desea ver el avance

El output es un diccionario donde sus keys son el enlace del artefacto y su value es otro diccionario con atributos _domain_, _type_, _size_, _date_ y _content_ en caso de ser tipo html

**Comment by mweitzman** [comment]
Funcionalidad implementada en develop en f8ea8ba
